GET /send-msg HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "msg": "Hello World",
  "author": "jaipal",
  "token": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "timestamp": {
    "hr":20,
    "min": 21
  }
}
