/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.HashMap;

import org.json.simple.parser.*;
import org.json.simple.JSONObject;

class Output implements JsonObj {
	public String output;
	public Output(String out) {
		output = out;
	}

	@Override
	public String toJson() {
		return String.format("{\"output\":\"%s\"}", output);
	}
}

public class App {
	public static void main(String[] args) {
		ArrayList<User> users = new ArrayList<>();
		users.add(new User("jaipal", "dffe86797a27a6cc1e7d4f3b7628783bc1292f310eeb352148f62a993c30c027", 75));
		users.add(new User("hema", "hema007", 75));

		ArrayList<Message> messages = new ArrayList<>();
		Server server = new Server(8000);
		server.add_route("/", (request, response) -> {
			User user = User.readJsonHome(request.body);
			if (user == null) {
				response.writeJson(new Output("USER_404"));
				response.statusCode = 401;
				return;
			}
			for (User el : users) {
				if (el.name.equalsIgnoreCase(user.name) && user.token.equals(el.token)) {
					if (messages.size() == 0) {
						response.writeJson(new Output("NO_MSG"));
					} else {
						response.writeJson(messages.get(messages.size() - 1));
					}
					return;
				}
			}
			response.setStatusCode(401);
			response.writeJson(new Output("USER_404"));
		});
		server.add_route("/login", (request, response) -> {
			User user = User.readJsonAuth(request.body);
			if (user == null) {
				response.writeJson(new Output("USER_404_LOGIN"));
				return;
			}
			for (User el : users) {
				if (el.name.equalsIgnoreCase(user.name) && el.password.equals(user.password)) {
					response.writeJson(el);
					return;
				}
			}
			response.setStatusCode(401);
			response.writeJson(new Output("USER_404_LOGIN"));
		});
		server.add_route("/send-msg", (request, response) -> {
			Message message = Message.readJson(request.body);
			if (message == null) {
				response.setStatusCode(400);
				response.writeJson(new Output("MSG_404"));
				return;
			}
			for (User el : users) {
				if (el.name.equalsIgnoreCase(message.sender) && el.token.equals(message.token)) {
					messages.add(message);
					response.writeJson(new Output("MSG_SENT"));
					return;
				}
			}
			response.writeJson(new Output("MSG_USER_404"));
		});
		server.start();
	}
}
